[package]
name = "opentelemetry-python-sdk"
version = "0.1.0"
edition = "2021"

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }

[build-dependencies]
pyo3-build-config.workspace = true
